[project]
name = "agentic-demo"
version = "0.1.0"
description = "MCP RAG Server for Warplane Information"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[project.optional-dependencies]
dev = [
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
